function [F,H,G] = jacobian_matrix(estimated_states,inputs,one_step_prediction)


phi = estimated_states(1);
theta = estimated_states(2);
psi = estimated_states(3);
b_p = estimated_states(4);
b_q = estimated_states(5);
b_r = estimated_states(6);

p_m = inputs(1);
q_m = inputs(2);
r_m = inputs(3);

g = 9.8;

F = [     sin(phi)*tan(theta)*(b_r - r_m) - cos(phi)*tan(theta)*(b_q - q_m),               - cos(phi)*(b_r - r_m)*(tan(theta)^2 + 1) - sin(phi)*(b_q - q_m)*(tan(theta)^2 + 1), 0, -1, -sin(phi)*tan(theta), -cos(phi)*tan(theta); ...
    cos(phi)*(b_r - r_m) + sin(phi)*(b_q - q_m),                                                                                                 0, 0,  0,            -cos(phi),             sin(phi); ...
    (sin(phi)*(b_r - r_m))/cos(theta) - (cos(phi)*(b_q - q_m))/cos(theta), - (cos(phi)*sin(theta)*(b_r - r_m))/cos(theta)^2 - (sin(phi)*sin(theta)*(b_q - q_m))/cos(theta)^2, 0,  0, -sin(phi)/cos(theta), -cos(phi)/cos(theta); ...
    0,                                                                                                 0, 0,  0,                    0,                    0; ...
    0,                                                                                                 0, 0,  0,                    0,                    0; ...
    0,                                                                                                 0, 0,  0,                    0,                    0];

phi = one_step_prediction(1);
theta = one_step_prediction(2);
psi = one_step_prediction(3);
% H = [                      0,          g*cos(theta), 0, 0, 0, 0;...
%     -g*cos(phi)*cos(theta), g*sin(phi)*sin(theta), 0, 0, 0, 0; ...
%     g*cos(theta)*sin(phi), g*cos(phi)*sin(theta), 0, 0, 0, 0; ...
%     0,0,1,0,0,0];

H = [1,0, 0, 0, 0, 0;...
    0,1, 0, 0, 0, 0;...
    0,0, 1, 0, 0, 0];
G = [ 1, sin(phi)*tan(theta), cos(phi)*tan(theta);...
    0,            cos(phi),           -sin(phi);...
    0, sin(phi)/cos(theta), cos(phi)/cos(theta);...
    0,                   0,                   0;...
    0,                   0,                   0;...
    0,                   0,                   0];

  